spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/intelligent_farming?serverTimezone=GMT%2B8
    username: root
    password: 
  redis:
    host: 
    port: 6379
    password: 

server:
  port: 8000

mqtt:
  util:
    url: 
    clientId: 
    topic: 
    timeout: 
    qos: 
#      username:
#      password:
  sensor:
    property:
      url: 
      clientId: 
      topic: 
      timeout: 
      qos: 
#      username:
#      password:
    event:
      url: 
      clientId: 
      topic: 
      timeout: 
      qos: 
#      username:
#      password:
