spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: root
    password: 
  redis:
    host: 
    port: 6379
    password: 

server:
  port: 8000

mqtt:
  util:
    url: 
    clientId: 
    topic: 
    timeout: 86400000
    qos: 1
#      username:
#      password:
  sensor:
    property:
      url: 
      clientId: 
      topic: 
      timeout: 86400000
      qos: 1
#      username:
#      password:
    event:
      url: 
      clientId: 
      topic: 
      timeout: 86400000
      qos: 1
#      username:
#      password: